### ISSUE TITLE
Minigame request

### ISSUE THREAD

**Issue by dylanblauw** [SilverstoneMC/Silverstone#38]
Plugin: https://www.spigotmc.org/resources/paintball-battle-team-minigame-1-8-1-16.76676/

Idea: I would like to recommend the paintball minigame. A game to throw snowballs at each other and upgrade your weapons. You could use other plugins that suit you best. My part of this will be the following. I WILL BUILD ALL YOUR MAPS. 3 minimum 7 max. I'll start immediately when approving this request. Let me know if you're interested.

I will play this game weekly. Why do you ask? Well xD because I made these games on every server I owned.

Message me!

**Comment by JasonHorkles** [comment]
I've decided this likely won't happen due to all the other projects lined up, so I'll be closing this request.
