### ISSUE TITLE
Clear entities Clear breeded Animals 

### ISSUE THREAD

**Issue by Dio0000** [SilverstoneMC/Silverstone#49]
the clear feature clears all breaded animals including the original ones. and the spawner shops don't have all animal spawners such as bee spawner, making a lot of the farms not possible. is just not practical to go out 10k blocks and leash 2 bees back to home ( even with flying) then before i can name them, they got cleared.

I propose either add more animal spawners to the shop or spawn eggs

or

don't clear the breaded animals

**Comment by JasonHorkles** [comment]
Bees are rather laggy when it comes to server performance, however, it may be fine to make the plugin not remove entities that were bred
I'll take a closer look in a few days

**Comment by Dio0000** [comment]
Btw is jungle biome disabled? I’ve been flying for days trying to find bamboo used all my rtps and travels more than 30k blocks and I haven’t seen a single jungle biome.

**Comment by JasonHorkles** [comment]
They're not, but they seem to be rather hard to find on this seed.

**Comment by Dio0000** [comment]
Could you add the jungle items to the shops instead, I’ve figured out how to spawn bees naturally.

Found a mushroom island but no jungle biome, I really don’t want to spend another 10 hours just to look for bamboo and jungle logs coco beans etc. Not sure if other players have found a jungle before, since no one is on recently I’m out of options.

Thanks very much

**Comment by JasonHorkles** [comment]
We plan to change the shop items a bit for season 2. Players likely aren't playing often because of the new season coming soon

**Comment by Dio0000** [comment]
Will the server reset for the new season?

**Comment by JasonHorkles** [comment]
Yes, that's what the big announcement is in the discord server that we keep warning about

**Comment by Dio0000** [comment]
Oh rip, I don’t have discord.

But thanks for letting me know

**Comment by JasonHorkles** [comment]
I recommend getting it if you're able to, as I'll be able to respond to stuff on there much quicker as well
