### ISSUE TITLE
Higher-level/stacked spawners stack with lower spawners

### ISSUE THREAD

**Issue by n0TaN00b473** [SilverstoneMC/Silverstone#51]
### World the issue occured in

Main

### My Minecraft username

n0TaN00b473

### What I was doing before/when the issue occurred

I found a mineshaft and a cave spider spawner. I thought I would add it to my spider farm, which had I think a 3 stack cave spider spawner. 

### What happened

When I picked it up, it stacked with my 3 spider spawner with the 1 spawner and changed it to a 1. 

### What was supposed to happen

They weren't supposed to stack

### Additional details

![image](https://user-images.githubusercontent.com/69173157/122704605-480caf80-d211-11eb-9a59-25429cb16db2.png)

**Comment by JasonHorkles** [comment]
Unable to reproduce.
I've updated the plugin but if you can reproduce it in a video leave a comment on this issue
