### ISSUE TITLE
Download Request

### ISSUE THREAD

**Issue by Dio0000** [SilverstoneMC/Silverstone#55]
### My Minecraft username

xXI___DIO___IXx

### My Discord username and tag

Dior#8038

### The first x & z coordinates of the area

18259, 1342

### The second x & z coordinates of the area

18205, 1288

### World of the area I'd like to save

Main

### How would you like the download?

Both

**Comment by JasonHorkles** [comment]
Closed as per request

**Comment by JasonHorkles** [comment]
Closed as per request
