### ISSUE TITLE
Outpost dosnt spawn pillagers and Village dont have bells

### ISSUE THREAD

**Issue by Dio0000** [SilverstoneMC/Silverstone#58]
### World the issue occured in

Survival

### My Minecraft username

xXI___DIO___IXx

### What I was doing before/when the issue occurred

exploring 

### What happened

pillager outpost dose not spawn pillagers, the flags are white, to me it seems it just generated the structure but it dosnt count as a actual outpost  without pillagers we won't have hero of the village benefit.  

village dosnt spawn bell
bell determines the village center used to spawn golems etc. it is a very important item. if the plugin does not generate them then pls add them in the shop as bells cannot be obtained by crafting 

### What was supposed to happen

pillager natural spawning

village generate bell as the center and spawn golems by its self

**Comment by RealTrashPanda** [comment]
I have found bells in some villages, they are just in the top of what I assume is the church.
![image](https://user-images.githubusercontent.com/39451403/125165546-c3db9580-e1da-11eb-873b-2befa8bebd5f.png)

**Comment by JasonHorkles** [comment]
Yeah there are some smaller and larger villages, and the larger ones should have the church with the bell
