### ISSUE TITLE
Spruce 2x2 tree not growing

### ISSUE THREAD

**Issue by RealTrashPanda** [SilverstoneMC/Silverstone#59]
### World the issue occured in

Survival

### My Minecraft username

Redstone_Master6

### What I was doing before/when the issue occurred

Planted 2x2 spruce saplings

### What happened

they did not grow

### What was supposed to happen

they were meant to grow

### Additional details

other saplings seem to work

**Comment by JasonHorkles** [comment]
Reported at https://github.com/PolyhedralDev/Terra/issues/248

**Comment by JasonHorkles** [comment]
Will be fixed in Season 3
