### ISSUE TITLE
named mob despawn bug

### ISSUE THREAD

**Issue by Error701** [SilverstoneMC/Silverstone#61]
### World the issue occured in

Survival

### Location

n/a

### My Minecraft username

Chilling_frost

### What I was doing before/when the issue occurred

I was messing around and a baby zombie with full gold armor spawned, so as a joke and to show a friend of mine, I put it in a boat. he laughed and suggested we name it "DonutKing", so I did and we were going to ss it as a joke, but right before I hit the button it despawned.

### What happened

The named mob shouldnt have despawned

### What was supposed to happen

it was supposed to say cheese, and smile as I screen shot it.

### Additional details

I then spent an hour trying to re create it and failed.

**Comment by JasonHorkles** [comment]
I'm unable to reproduce the issue
