### ISSUE TITLE
Grief Report

### ISSUE THREAD

**Issue by SoulzMC** [SilverstoneMC/Silverstone#63]
### My Minecraft username

SoulzMC

### World of the grief

Survival

### The coordinates at the location of the grief

-4016, 59, -3175

### What happened

![2021-08-21_15 21 59](https://user-images.githubusercontent.com/89318358/130332767-b8a018b3-1df1-4b02-a348-77501cb1dae1.png)

**Comment by JasonHorkles** [comment]
Resolved by player
