### ISSUE TITLE
Grief Report/Land Dispute 

### ISSUE THREAD

**Issue by LoneWolfAdam** [SilverstoneMC/Silverstone#69]
### My Minecraft username

Lone Wolf Adam 

### World of the grief

Survival

### The coordinates at the location of the grief

5986, -3625 

### What happened

I am in a current land dispute with player "big daddy" i made a claim on a chain of floating islands 6 or 7 days ago (todays date is 11/14/21)  and  when i made my claim no other buildings there, but today (11/14/21) at 12:30 AM i was pinged in your server saying "unclaim the area u claimed by us" in which the following evening i was made aware by user/mod "Dragon" that there was a building on my chain of islands, which i where not there when i first started building there. with this I would like to see who had claims first or maybe we can come to and agreement on sharing the island chain as i have put countless hours into this space and i dont wanna see it be for waste.

**Comment by JasonHorkles** [comment]
After some investigation, players `_BigDaddy_` and `yumikitten` had originally found and interacted with the islands. However, `LoneWolfAdam` was the first to actually begin building on the land. Therefore, if `_BigDaddy_` and `yumikitten` have built within 300 blocks (which they have) of a base that's not theirs without their permission, they are deemed the ones violating rule 11.


In conclusion, the land is rightfully owned by you, `LoneWolfAdam`, and you may choose between the following options:
A) Become friendly neighbors with each other
B) Kindly ask the players to move elsewhere, and if they don't comply, submit a report and their builds will be removed

**Comment by LoneWolfAdam** [comment]
I take option B as both have been aggressive in the past, altho there has been a little kindness which leaves me with a statement. 

"I will allow you (or anyone) to rent space on my chain of islands price (in game items like food, diamonds or other stuff*) can be talked about else where but as the owner i do have the right to kick you off whenever i see fit/choose other terms and conditions apply" 

and if you dont feel like renting space please remove yourself from my islands in the next 48 hours
