### ISSUE TITLE
Sodium Mod

### ISSUE THREAD

**Issue by BareTuna** [SilverstoneMC/Silverstone#70]
### The mod's ID

sodium

### Link to the mod

https://www.curseforge.com/minecraft/mc-mods/Sodium

### Why I think the mod should be whitelisted

It's like OptiFine but for **Fabric**. It is specifically focused on performance, so there aren't extra features that would disallow it from the whitelist.

**Comment by JasonHorkles** [comment]
Fabric doesn't provide a mod list like Forge does, so we can't technically restrict what mods are used on Fabric anyways. Because Forge no longer works properly on servers, we'll be removing the mod whitelist when Season 3 begins.
