### ISSUE TITLE
Download Request

### ISSUE THREAD

**Issue by LoneWolfAdam** [SilverstoneMC/Silverstone#72]
### The first x & z coordinates of the area

10k

### The second x & z coordinates of the area

-10k

### World of the area I'd like to save

Survival

### How would you like the download?

World File (.zip, can be extracted directly into the "worlds" folder - $3 USD fee)

**Comment by JasonHorkles** [comment]
The following download will expire at the end of the month: https://1drv.ms/u/s!ArOS099NaR9LntYKmIlSIVMU0FmhjA?e=fDcuPR
