### ISSUE TITLE
Staff Application

### ISSUE THREAD

**Issue by LoneWolfAdam** [SilverstoneMC/Silverstone#73]
### Am I re-submitting my application?

No

### My Minecraft username

LoneWolfAdam 

### My Discord username & tag

Lone Wolf Adam#6969

### My current rank

MVP

### My total time played on the server (in hours)

136 hours

### My current age

18

### Why I want to be a staff member

I feel like I could add some humor to the team along with be someone who is constantly active an having fun. I also bring a good few people into the server as I am a builder and head of a community/neighborhood in both season 2 and 3 of the Silverstone survival server. I would like to be a staff member as I feel like I can provide a watchful eye to the server and its members along with being helpful! Not only am I willing to help and hang out with others I dont back down from a challenge and am not afraid to ask for help! Overall I just wanna give back and help out to the place that I've been able to call home!

### How often am I / will I be active on the Minecraft server?

Average 6-10 hours a week 

### How often am I / will I be active in the Discord server?

I'm on discord near 18 hours a day even throughout school and other times. 

### On a scale of 1-10, how good of a staff member do I think I'd be?

7

### Do I feel like I'm worthy of being a Silverstone staff member?

I sure do! I will need to be taught but I'm willing to do my best!

### Do I swear I'll do my best to follow and enforce the server rules at all times?

Absolutely!

### Explanation

I feel like I should be a moderator/staff member as I wanna help out and server others! I enjoy people and am highly interactive! I also have 3+ years of experience on discord and know how to use it rather well. Overall I think I would be added to the staff team to bring in some fresh light and fill in gaps where other staff members cant!

**Comment by JasonHorkles** [comment]
Congratulations! You will now begin the Trial Mod phase for 1 week.
