### ISSUE TITLE
plugin issue

### ISSUE THREAD

**Issue by OFIVEMEMBER** [SilverstoneMC/Silverstone#75]
### World the issue occured in

Survival

### My Minecraft username

SCP___682

### What I was doing before/when the issue occurred

i was in school before the bug / issue / glitch happened

### What happened

so far 
keep inventory
claims
other features the plugin added 
all down, example , me and my friend stay in the claim/protected area , and usually when leaving it says "exiting ???'s protected area" but now it didn't , it just did nothing , i went to check on an other guys claim area but there never was anything that said entering ???'s protected area

### What was supposed to happen

non of this should have happened

### Additional details

maybe go check into what doesn<t work anymore becose not all the plugin's features work

**Comment by JasonHorkles** [comment]
Thanks for the report. The bug has been fixed.
