### ISSUE TITLE
Issue on hard flying course

### ISSUE THREAD

**Issue by StarscapeNW17** [SilverstoneMC/Silverstone#79]
### World the issue occured in

flying_course

### Location

24 125 76

### My Minecraft username

thebirdlady17

### What I was doing before/when the issue occurred

I leave the flying course main area and try to do the hard course 

### What happened

Player does not turn translucent, doesn't get teleported when you hit blocks (except for barriers), and pink booster blocks do not work

### What was supposed to happen

opposite of what happened lol

### Additional details

(video) https://cdn.discordapp.com/attachments/569671094131228672/1191138420328759379/Untitled_video_1.mp4?ex=65ee2d19&is=65dbb819&hm=1e8c40113486263bfa428e1d5cad86b3ab00bfb869b16e48fb253b6fa2dc4d87&
![image (2)](https://github.com/SilverstoneMC/Silverstone/assets/83558490/396281e5-eb2d-4dea-b7e6-e02c98b247bd)
![image1](https://github.com/SilverstoneMC/Silverstone/assets/83558490/f844412e-e28c-4294-b30f-b9faa2819e18)

**Comment by JasonHorkles** [comment]
This is possibly fixed? I can't reproduce it but let me know if it happens again.
