### ISSUE TITLE
Corrupted tag doorway does damage.

### ISSUE THREAD

**Issue by Breaadhead** [SilverstoneMC/Silverstone#81]
### World the issue occured in

minigames

### My Minecraft username

Breadheadd

### What I was doing before/when the issue occurred

Walking out the doorway for corrupted tag.

### What happened

Fireworks happen to deal damage, so the firework entrance effect when the door opens for the corrupted tag player will deal some damage to the person.

### What was supposed to happen

Damage should not have happened

**Comment by JasonHorkles** [comment]
You sure it wasn't just your health limiter being applied? Fireworks are set to not do any damage
